### ISSUE TITLE
Practica de hilos 

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/practica-de-hilos-Nayee123#2]
[Practica_hilos_Nayeli_Anai_G.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Nayee123/files/6498124/Practica_hilos_Nayeli_Anai_G.pdf)

**Comment by Rosa218** [comment]
Calificación:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
